--liquibase formatted sql

--changeset brunoestrai:1
CREATE TABLE CPF (
    CPF VARCHAR(11) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT PK_CPF PRIMARY KEY (CPF)
);